AustinSamples/Models/FileUploadMD.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace AustinSamples.Models
{
    public class FileUploadMD
    {
        //[Required(ErrorMessage = "Please select file.")]
        //[RegularExpression(@"([a-zA-Z0-9\s_\\.\-:])+(.png|.jpg|.gif|.jpeg|.pdf)$", ErrorMessage = "Only Image files allowed.")]
        public HttpPostedFileBase PostedFile { get; set; }
    }
}

AustinSamples/Models/IncidentMD.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AustinSamples.Models
{
    public class IncidentMD
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Country { get; set; }
        public string Gender { get; set; }
        public bool IsMarried { get; set; }
    }
}

AustinSamples/Controllers/ExpController.cs
using AustinSamples.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AustinSamples.Controllers
{
    public class ExpController : Controller
    {
        // GET: Exp
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult UploadImage()
        {
            return View();
        }

        [HttpPost]
        public ActionResult UploadImage(HttpPostedFileBase postedFile)
        {
            string path = Server.MapPath("~/UploadedFiles/");
            if (!Directory.Exists(path))
            {
                Directory.CreateDirectory(path);
            }

            if (postedFile != null)
            {
                string fileName = Path.GetFileName(postedFile.FileName);
                postedFile.SaveAs(path + fileName);
                ViewBag.Message += string.Format("<b>{0}</b> uploaded.<br />", fileName);
            }

            return View();
        }

        public ActionResult DynamicGrid()
        {
            
            
            return View();
        }

        [HttpGet]
        public JsonResult AjaxMethod()
        {
            if (Session["MyData"] == null)
            {
                List<IncidentMD> entities = new List<IncidentMD>()
               {
                new IncidentMD(){ Id=1, Name="Bill", Country="India",Gender="Male",IsMarried=true},
                new IncidentMD(){ Id=2, Name="Steve",Country="India",Gender="Male",IsMarried=true},
                new IncidentMD(){ Id=3, Name="Ram",Country="India",Gender="Male",IsMarried=true },
                new IncidentMD(){ Id=4, Name="Moin",Country="India",Gender="Male",IsMarried=true}
                };
                Session["MyData"] = entities;
                return Json(entities, JsonRequestBehavior.AllowGet);
            }
            else
            {

                List<IncidentMD> entities= Session["MyData"] as List<IncidentMD>;
                return Json(entities, JsonRequestBehavior.AllowGet);

            }

        }

        [HttpGet]
        public JsonResult GetCountries()
        {
            List<String> countries = new List<String>();
            countries.Add("India");
            countries.Add("USA");
            countries.Add("Africa");
            countries.Add("Bali");
            countries.Add("GreenLand");
            
            return Json(countries, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public JsonResult InsertCustomers(List<IncidentMD> customers)
        {

                Session["MyData"] = customers;
                return Json(new { Success = true});

        }

    }
}

AustinSamples/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AustinSamples.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

AustinSamples/Views/Exp/DynamicGrid.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <style type="text/css">
        body {
            font-family: Arial;
            font-size: 10pt;
        }

        table {
            border: 1px solid #ccc;
            border-collapse: collapse;
            background-color: #fff;
        }

            table th {
                background-color: #B8DBFD;
                color: #333;
                font-weight: bold;
            }

            table th, table td {
                padding: 5px;
                border: 1px solid #ccc;
            }

            table, table table td {
                border: 0px solid #ccc;
            }

        .Pager span {
            text-align: center;
            color: #333;
            display: inline-block;
            width: 20px;
            background-color: #B8DBFD;
            margin-right: 3px;
            line-height: 150%;
            border: 1px solid #B8DBFD;
        }

        .Pager a {
            text-align: center;
            display: inline-block;
            width: 20px;
            background-color: #ccc;
            color: #333;
            border: 1px solid #ccc;
            margin-right: 3px;
            line-height: 150%;
            text-decoration: none;
        }
    </style>
   
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            debugger
            //Call EmpDetails jsonResult Method
            $.getJSON("/Exp/AjaxMethod",
                function (json) {
                    var tr;
                    //Append each row to html table
                    for (var i = 0; i < json.length; i++) {
                        tr = $('<tr/>');
                        tr.append("<td><input type='checkbox' name='IsDelete' value='IsDelete'></td>");
                        tr.append("<td>" + json[i].Id + "</td>");
                        tr.append("<td>" + json[i].Name + "</td>");
                        tr.append("<td>" + json[i].Country + "</td>");
                        tr.append("<td>" + json[i].Gender + "</td>");
                        tr.append("<td>" + json[i].IsMarried + "</td>");
                        $('table').append(tr);
                    }
                });

            $(".add-row").click(function () {
                
                AddRow();
                
             });

             $(".delete-row").click(function () {
                $("table tbody").find('input[name="IsDelete"]').each(function () {
                    if ($(this).is(":checked")) {
                        $(this).parents("tr").remove();
                    }
                });
            });


              function AddRow() {
                
                var td = "<td class=" + "select" + ">";
                $.getJSON("/Exp/GetCountries",
                    function (json) {
                        
                        var dd = "<select id=" + "countrySelect" + ">";
                            
                        $.each(json, function (index, value) {
                            
                                dd += "<option value='" + value + "'>" + value + "</option>";
                                //$('<option>').val(value).text(value).appendTo("#countrySelect");
                            });

                        dd += "</select>";

                        td += dd + "</td>";
                        var markup = "<tr>" +
                            "<td><input type='checkbox' name='IsDelete' value='IsDelete'></td>" +
                            "<td><input type='text' name='Id'></td>" +
                            "<td><input type='text' name='Name'></td>" +
                             td +
                            "<td>" +
                            "<input type=" + "radio" + " id=" + "male" + "name=" + "gender" + "value=" + "male" + ">" +
                            "<label for=" + "male" + ">Male</label>" +
                            "<input type=" + "radio" + " id=" + "female" + "name=" + "gender" + "value=" + "female" + ">" +
                            "<label for=" + "male" + ">Female</label>" +
                            "</td > " +
                            "<td><input type='checkbox' name='IsMarried' value='IsMarried'></td>" +
                            "</tr>";
                            $("table tbody").append(markup);
                });
                return td;
            }

            $(".Save").click(function () {
                debugger
                //Loop through the Table rows and build a JSON array.
                var customers = new Array();
                $("#tblCustomers TBODY TR").each(function (a,b) {
                    debugger
                    var row = $(this);
                    var customer = {};
                   
                    customer.Id = row.find("TD").eq(1).html();
                    customer.Name = row.find("TD").eq(2).html();
                    customer.Country = row.find("TD").eq(3).html();
                    customer.Gender = row.find("TD").eq(4).html();
                    customer.IsMarried = row.find("TD").eq(5).html();
                    customers.push(customer);
                });

                //Send the JSON array to Controller using AJAX.
                $.ajax({
                    type: "POST",
                    url: "/Exp/InsertCustomers",
                    data: JSON.stringify(customers),
                    contentType: "application/json; charset=utf-8",
                    dataType: "json",
                    success: function (r) {
                        alert(r + " record(s) inserted.");
                    }
                });
            });

            function AddRowToArray() {
                var customers = new Array();

            }

           
            
           
        });
        
    </script>
</head>
<body>
    <input type="button" class="add-row" value="Add Row">
    <input type="button" class="delete-row" value="Delete Row">
    <input type="button" class="Save" value="Save All">

    <table class="table table-bordered table-condensed table-hover table-striped" id="tblCustomers">
        <thead>
            <tr>
                <th></th>
                <th>Id</th>
                <th>Name</th>
                <th>Country</th>
                <th>Gender</th>
                <th>IsMarried</th>

            </tr>
        </thead>
        <tbody></tbody>
    </table>
</body>
</html>

AustinSamples/Views/Exp/UploadImage.cshtml
@model AustinSamples.Models.FileUploadMD

@{
    Layout = null;
}

<!DOCTYPE html>


    <style type="text/css">
        body {
            font-family: Arial;
            font-size: 10pt;
        }

        .error {
            color: red;
        }
    </style>


   <div>
        @using (Html.BeginForm("UploadImage", "Exp", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <span>Select File:</span>
            @Html.TextBoxFor(m => m.PostedFile, new { type = "file", @onchange = "ValidateSingleInput(this);" })
            <br />
            @Html.ValidationMessageFor(m => m.PostedFile, "", new { @class = "error" })
            <hr />
            <input type="submit" value="Upload" />
            <br />
            <span style="color:green">@Html.Raw(ViewBag.Message)</span>
        }
    </div>
<script>
 var _validFileExtensions = [".jpg", ".jpeg", ".bmp", ".gif", ".png",".pdf"];    
function ValidateSingleInput(oInput) {
    if (oInput.type == "file") {
        var sFileName = oInput.value;
         if (sFileName.length > 0) {
            var blnValid = false;
            for (var j = 0; j < _validFileExtensions.length; j++) {
                var sCurExtension = _validFileExtensions[j];
                if (sFileName.substr(sFileName.length - sCurExtension.length, sCurExtension.length).toLowerCase() == sCurExtension.toLowerCase()) {
                    blnValid = true;
                    break;
                }
            }
             
            if (!blnValid) {
                alert("Sorry, " + sFileName + " is invalid, allowed extensions are: " + _validFileExtensions.join(", "));
                oInput.value = "";
                return false;
            }
        }
    }
    return true;
}
</script>

AustinSamples/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

AustinSamples/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

AustinSamples/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

AustinSamples/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>